### ISSUE TITLE
FEAT: Generate another recipe on RecipePage

### ISSUE THREAD

**Issue by ThiiLuu79** [CookingLab/cooking-lab#38]
As a user, on the recipe page, I want to be able to generate another recipe by clicking on a button if the current recipe does not match my needs.

UI:
![Image](https://github.com/user-attachments/assets/46a5487a-0bb5-405f-b735-a7c2b652ad8e)

Acceptance criterias: 
- [x] Recipe page should have a "Generate another recipe" button
- [x] On click, the button should generate another recipe
- [x] User's input should remain the same when clicking on the button
- [x] Generate Another Recipe should be disabled when generating a Quick Recipe
- [x] Include unit and e2e tests

**Comment by tien-chung** [comment]
@ThiiLuu79 Added the "Generate another recipe" button

![Image](https://github.com/user-attachments/assets/cef26493-1473-4214-a2a7-dad4dfad6264)

**Comment by ThiiLuu79** [comment]
> @ThiiLuu79 Added the "Generate another recipe" button
> 
> ![Image](https://github.com/user-attachments/assets/cef26493-1473-4214-a2a7-dad4dfad6264)
> 

Looks good 👍
