### ISSUE TITLE
FEAT: Our recipes

### ISSUE THREAD

**Issue by ThiiLuu79** [CookingLab/cooking-lab#45]
As a developer of Cooking Lab, I want to have an option to display my personal recipes, so I can share them with Cooking Lab's users.

UI:
![Image](https://github.com/user-attachments/assets/6188e316-1f13-4cf1-9af7-d83b8e932683)

Acceptance criterias:

**BACKEND (new API)**
 - [x] Create an API that exposes personal recipes.
    - [x] Should have an id field (int).
    - [x] Should have a title field (String).
    - [x] Should have a ingredients field (String[]).
    - [x] Should have a instructions field (String[]).
    - [x] Should have a imageURL field (String). 
 - [x] Populate recipes.json
 - [x] Deploy the API

**UI**
 - [x] In the navbar, section "See our recipes". This will redirect to a new page.
 - [x] On Our recipe page, we will have 2 sections. One with Tien recipe and the other with TM recipe.
 - [x] Each sections should have their respectives recipes (sorted by owner={target_owner})
 - [x] When clicking on a recipe, redirect to the recipe page with the correct information.
 - [x] When landing on Our recipe page, display a loader until the api call is done.
 - [x] On recipe page, when is consulting a personal recipe, the following criterias should be respected:
     - [x] Instructions should be added
     - [x] Link should be hidden
     - [x] Generate another should be hidden
     - [x] Restart button should be hidden
     - [x] Back button should redirect to Our recipe page
     - [x] Image should be shown.
- [x] Unit tests
- [x] Cypress tests

**Comment by ThiiLuu79** [comment]
Personal recipe API is created : https://github.com/CookingLab/cooking-lab-personal-recipe-api

**Comment by ThiiLuu79** [comment]
Deployed! The URL to be called is https://cooking-lab-personal-recipe-ap-93e4f56ab86c.herokuapp.com/api/recipes/personal

**Comment by ThiiLuu79** [comment]
Deployed on render.
Hosted on https://cooking-lab-personal-recipe-api.onrender.com

**Comment by tien-chung** [comment]
"See our recipes" page can be accessed at https://cooking-lab.netlify.app/personalRecipe

**Comment by ThiiLuu79** [comment]
@tien-chung 
For now, the image can be an image taken from the internet.
To proceed, we need to modify the api and add an additional attribute (imageURL) to the model and the JSON.

We will proceed this way for the time being, while we investigate on how to add our own images.

**Comment by ThiiLuu79** [comment]
recipes.json is populated : https://github.com/CookingLab/cooking-lab-personal-recipe-api/blob/main/src/main/resources/recipes.json

**Comment by tien-chung** [comment]
Unit tests for personal recipes are completed

![Image](https://github.com/user-attachments/assets/03d77993-7843-492c-94e3-25c0ad083dfe)
